alias cat='batcat'
alias catalias='cat ~/.aliases.zsh'
alias cb='snap run clipboard'
alias cab='catkin build'
alias cmb='cmake --build build -j'
alias cc='clear'
alias cleartmp='rm -rf ~/tmp/*'
alias cm='cmake -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
alias copydir='pwd | tr "\n" "\b" | xclip -selection clipboard'
alias dk='cd ~/Desktop'
alias dn='cd ~/Downloads'
alias doc='cd ~/Documents'
alias docker_clean_images='docker rmi $(docker images -a --filter=dangling=true -q)'
alias docker_clean_ps='docker rm $(docker ps --filter=status=exited --filter=status=created -q)'
alias gc='git commit'
alias gcl='git clone'
alias gco='git checkout'
alias gdown='gsutil -m cp'
alias git_pull_all='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;'
alias git_stash_all='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} stash \;'
alias git_status_all='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} status \;'
alias gp='git push'
alias py='ipython3'
alias rf='rm -rf'
alias rg='ranger'
alias ta='tmux attach -t'
alias ts='tmux new -s'
alias vim='nvim'
alias work='tmuxinator start -p ~/.work.yml $(basename $(pwd))'
alias perfo='tmuxinator start -p ~/.performance.yml $(basename $(pwd))'
alias xcopy='xclip -selection clipboard'
alias open='xdg-open'

