alias nv='nvim'
alias py='ipython3'
alias coex='code . && exit'
alias dk='cd ~/Desktop'
alias dn='cd ~/Downloads'
alias docu='cd ~/Documents'
alias catalias='cat ~/.aliases.zsh'
alias xopen='xdg-open'
alias gco='git checkout'
alias gcl='git clone'
alias xcopy='xclip -selection clipboard'
alias copywd='pwd | tr "\n" "\b" | xclip -selection clipboard'
alias ll='ls -hltrBF --group-directories-first --color=auto'
alias ts='tmux new-session -s $(basename $(pwd))'
alias rf='rm -rf'
alias source_roiws_debug='source ~/hrl/roi_ws/devel_debug/setup.zsh'
alias source_roiws_release='source ~/hrl/roi_ws/devel_release/setup.zsh'
alias df='df -h -xsquashfs -xtmpfs -xdevtmpfs'
alias docker_clean_images='docker rmi $(docker images -a --filter=dangling=true -q)'
alias docker_clean_ps='docker rm $(docker ps --filter=status=exited --filter=status=created -q)'
alias primary='xrandr --output HDMI-0 --primary --mode 1920x1080'
alias cc='clear'
alias cropbox='source ~/evitado/devel/setup.zsh && cropbox_editor'
alias evrelease='source /home/s/evitado_ws/devel_release/setup.zsh'
alias evdebug='source /home/s/evitado_ws/devel_debug/setup.zsh'
alias vimalias='vim ~/.aliases.zsh'
alias qtdesigner='/home/sumanth/.local/lib/python3.8/site-packages/qt5_applications/Qt/bin/designer'
alias see='watch -n 1'
alias mp='mkdir -p'
alias num_pts_pcd='/home/s/pyutils/number_of_points_pcd.py'
alias git_mpull='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;'
alias git_branches='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} status \;'
alias gdown='gsutil -m cp'
alias cleanpcd='python3 ~/clean_script.py'
alias notes='nvim ~/Desktop/thesis_notes'
alias merge_compile_commands='sh ~/scripts/merge_compile_commands'
alias esc_caps='sh ~/scripts/esc_to_capslock.sh'
alias enotes='nvim ~/Desktop/evitado_notes'
