# ./.tmuxinator.yml
name: <%= @args[0] %>
startup_window: editor
windows:
  - editor:
      layout: even-horizontal
      panes:
        - nvim . +E
        - 
  - run_baby_run:
      panes:
        - catkin_source
        - catkin_source 
        - catkin_source 
        - catkin_source 
